apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: logging
  labels:
    k8s-app: fluentd
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
  labels:
    k8s-app: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
  labels:
    k8s-app: fluentd
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: logging
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: ""
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: logging
  labels:
    k8s-app: fluentd
spec:
  ports:
  - port: 24224
    nodePort: 32188
    protocol: TCP
    targetPort: server
  selector:
    k8s-app: fluentd
    version: v2.2.1
  type: NodePort
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-config-v0.1.6
  namespace: logging
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
    </system>
  system.input.conf: |-
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>
    <match **>
      @type stdout
    </match>
  output.conf: |-
    # Enriches records with Kubernetes metadata
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
    <server>
      name fluentd-server
      host fluentd-server
      port 24224
      weight 100
     </server>

    <match **>
      @id elasticsearch
      @type elasticsearch
      @log_level info
      type_name fluentd
      include_tag_key true
      host elasticsearch-logging
      port 9200
      logstash_format true
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  namespace: logging
  labels:
    k8s-app: fluentd
    version: v2.2.1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd
      version: v2.2.1
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: fluentd
        version: v2.2.1
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: fluentd
      containers:
      - name: fluentd
        image: artifact.paas.yp/cicd-docker-local/fluentd-elasticsearch:v2.2.0
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/fluent/config.d
      terminationGracePeriodSeconds: 120
      imagePullSecrets:
      - name: myregistrykey
      volumes:
      - name: config-volume
        configMap:
          name: fluentd-config-v0.1.6